//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public int childID { get; set; }
        public Nullable<int> familyId { get; set; }
        public string firstName { get; set; }
        public Nullable<int> age { get; set; }
        public string sax { get; set; }
        public Nullable<System.DateTime> dateEntryToSite { get; set; }
        public string status { get; set; }
        public string tz { get; set; }
    
        public virtual family family { get; set; }
    }
}
