//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class volunteeringEntities1 : DbContext
    {
        public volunteeringEntities1()
            : base("name=volunteeringEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<child> child { get; set; }
        public virtual DbSet<childEvent> childEvent { get; set; }
        public virtual DbSet<eventOfChild> eventOfChild { get; set; }
        public virtual DbSet<eventOfVolunteer> eventOfVolunteer { get; set; }
        public virtual DbSet<eventsVolunteer> eventsVolunteer { get; set; }
        public virtual DbSet<family> family { get; set; }
        public virtual DbSet<secretary> secretary { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<typeDisability> typeDisability { get; set; }
        public virtual DbSet<volunteer> volunteer { get; set; }
        public virtual DbSet<volunteerHistory> volunteerHistory { get; set; }
        public virtual DbSet<volunteerOfChild> volunteerOfChild { get; set; }
    }
}
