//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeDisability
    {
        public int typeDisabilityID { get; set; }
        public string typeUser { get; set; }
        public int volunteerId { get; set; }
        public string hearing { get; set; }
        public byte[] incapacity { get; set; }
        public string communication { get; set; }
        public string violence { get; set; }
        public string ASD { get; set; }
        public string lag { get; set; }
        public string AHD { get; set; }
        public string downSyndrome { get; set; }
        public int childId { get; set; }
    
        public virtual volunteer volunteer { get; set; }
    }
}
