//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteerHistory
    {
        public int volunteerHistoryID { get; set; }
        public Nullable<int> volunteerId { get; set; }
        public Nullable<int> childId { get; set; }
        public Nullable<int> volunteerOfChildId { get; set; }
        public Nullable<int> volunteerQualityId { get; set; }
        public System.TimeSpan hour { get; set; }
        public System.DateTime dateVolunteer { get; set; }
        public string remarks { get; set; }
    
        public virtual child child { get; set; }
        public virtual volunteer volunteer { get; set; }
        public virtual volunteerOfChild volunteerOfChild { get; set; }
    }
}
