//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventOfChild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventOfChild()
        {
            this.childEvent = new HashSet<childEvent>();
            this.typeDisability = new HashSet<typeDisability>();
        }
    
        public int eventOfChildID { get; set; }
        public Nullable<int> organizingSecretary { get; set; }
        public string typeEvent { get; set; }
        public Nullable<System.DateTime> dateEvent { get; set; }
        public Nullable<int> maxNumChildren { get; set; }
        public Nullable<int> actualNumChildren { get; set; }
        public string placeEvent { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<childEvent> childEvent { get; set; }
        public virtual secretary secretary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<typeDisability> typeDisability { get; set; }
    }
}
