//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventOfVolunteer
    {
        public int volunteerOfEventID { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> volunteerId { get; set; }
        public Nullable<int> minCountVolunteering { get; set; }
        public Nullable<int> countVolunteer { get; set; }
        public string IsParticipant { get; set; }
    
        public virtual eventsVolunteer eventsVolunteer { get; set; }
        public virtual volunteer volunteer { get; set; }
    }
}
